# Generated by Django 6.0.6 on 2026-06-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('blood_group_needed', models.CharField(max_length=5)),
                ('hospital_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
    ]
